### ISSUE TITLE
Use Griffe's public API

### ISSUE THREAD

**Issue by pawamoy** [taikinman/langrila#139]
You're importing from the internal API:

https://github.com/taikinman/langrila/blob/de2ea7747631625ade0da4e0393e469db076f1a0/src/langrila/core/tool.py#L10-L12

and

https://github.com/taikinman/langrila/blob/de2ea7747631625ade0da4e0393e469db076f1a0/src/langrila/core/griffe.py#L10-L12

...exposing yourself to breakages.

Public equivalent:

```python
from griffe import DocstringSectionKind, Docstring, Object as GriffeObject 
```

**Comment by taikinman** [comment]
As you mentioned, public API only is the best.
Could you fix it and create PR? Otherwise I will fix soon.

**Comment by pawamoy** [comment]
Thanks for the quick response! Sure, I opened #140 :slightly_smiling_face:
